# Generated by Django 2.0.2 on 2018-03-31 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.Character')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterSpells',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('desc', models.CharField(max_length=100)),
                ('long_desc', models.CharField(max_length=1000)),
                ('keywords', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SubGuild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('attribute_level', models.CharField(max_length=20)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.Guild')),
            ],
        ),
        migrations.CreateModel(
            name='SubRace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.Race')),
            ],
        ),
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.Item')),
                ('attribute_type', models.CharField(max_length=100)),
            ],
            bases=('game.item',),
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.Item')),
                ('weapon_type', models.CharField(max_length=100)),
                ('damage_stat', models.CharField(max_length=10)),
                ('damage_type', models.CharField(max_length=20)),
            ],
            bases=('game.item',),
        ),
        migrations.AddField(
            model_name='item',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.Material'),
        ),
        migrations.AddField(
            model_name='characterspells',
            name='spell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.Spell'),
        ),
        migrations.AddField(
            model_name='character',
            name='guild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.Guild'),
        ),
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.Race'),
        ),
        migrations.AddField(
            model_name='character',
            name='subguild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.SubGuild'),
        ),
        migrations.AddField(
            model_name='bard',
            name='subguild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.SubGuild'),
        ),
        migrations.AddField(
            model_name='characterinventory',
            name='armor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.Armor'),
        ),
        migrations.AddField(
            model_name='characterinventory',
            name='weapon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.Weapon'),
        ),
    ]
