# Generated by Django 2.0.2 on 2018-03-31 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_race_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='desc',
            field=models.TextField(default=''),
        ),
    ]
