# Generated by Django 2.0.2 on 2018-03-31 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20180331_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subguild',
            name='attribute_level',
        ),
    ]
