# Generated by Django 2.0.2 on 2018-04-02 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_remove_subguild_attribute_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuildSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.Guild')),
            ],
        ),
    ]
