# Generated by Django 2.0.2 on 2018-04-05 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_character_subrace'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guild',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='race',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='subguild',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='subrace',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='character',
            name='subrace',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='game.SubRace'),
        ),
    ]
