# Generated by Django 2.0.2 on 2018-04-05 03:29

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20180404_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subrace',
            name='race',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='name', chained_model_field='race', on_delete=django.db.models.deletion.CASCADE, to='game.Race'),
        ),
    ]
