# Generated by Django 2.0.2 on 2018-04-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_auto_20180404_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='goodAlignment',
            field=models.CharField(choices=[('GOOD', 100), ('NEUTRAL', 50), ('EVIL', 0)], default='GOOD', max_length=20),
        ),
        migrations.AddField(
            model_name='character',
            name='lawfulAlignment',
            field=models.CharField(choices=[('LAWFUL', 100), ('NEUTRAL', 50), ('CHAOTIC', 0)], default='LAWFUL', max_length=20),
        ),
    ]
