# Generated by Django 2.0.2 on 2018-04-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_auto_20180407_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(default='')),
                ('acrobatics', models.BooleanField(default=0)),
                ('arcana', models.BooleanField(default=0)),
                ('athletics', models.BooleanField(default=0)),
                ('deception', models.BooleanField(default=0)),
                ('history', models.BooleanField(default=0)),
                ('insight', models.BooleanField(default=0)),
                ('intimidation', models.BooleanField(default=0)),
                ('investigation', models.BooleanField(default=0)),
                ('medicine', models.BooleanField(default=0)),
                ('nature', models.BooleanField(default=0)),
                ('perception', models.BooleanField(default=0)),
                ('performance', models.BooleanField(default=0)),
                ('persuasion', models.BooleanField(default=0)),
                ('religion', models.BooleanField(default=0)),
                ('sleight', models.BooleanField(default=0)),
                ('stealth', models.BooleanField(default=0)),
                ('survival', models.BooleanField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='character',
            name='goodAlignment',
            field=models.CharField(choices=[(100, 'Good'), (50, 'Neutral'), (0, 'Evil')], default='GOOD', max_length=20),
        ),
        migrations.AlterField(
            model_name='character',
            name='lawfulAlignment',
            field=models.CharField(choices=[(100, 'Lawful'), (50, 'Neutral'), (0, 'Chaotic')], default='LAWFUL', max_length=20),
        ),
    ]
