# Generated by Django 2.0.2 on 2018-04-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_auto_20180407_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='background',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='background',
            name='animal_handling',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='animal_handling',
            field=models.BooleanField(default=0),
        ),
    ]
