# Generated by Django 2.0.2 on 2018-04-07 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_auto_20180407_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='background',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='game.Background'),
        ),
    ]
