# Generated by Django 2.0.2 on 2018-04-07 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_skill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ('name',)},
        ),
        migrations.RenameField(
            model_name='background',
            old_name='acrobatics',
            new_name='Acrobatics',
        ),
        migrations.RenameField(
            model_name='background',
            old_name='animal_handling',
            new_name='Animal_handling',
        ),
        migrations.RenameField(
            model_name='background',
            old_name='arcana',
            new_name='Arcana',
        ),
        migrations.RenameField(
            model_name='background',
            old_name='athletics',
            new_name='Athletics',
        ),
        migrations.RenameField(
            model_name='background',
            old_name='deception',
            new_name='Deception',
        ),
        migrations.RenameField(
            model_name='background',
            old_name='history',
            new_name='History',
        ),
        migrations.RenameField(
            model_name='background',
            old_name='insight',
            new_name='Insight',
        ),
        migrations.RenameField(
            model_name='background',
            old_name='intimidation',
            new_name='Intimidation',
        ),
        migrations.RenameField(
            model_name='background',
            old_name='investigation',
            new_name='Investigation',
        ),
        migrations.RenameField(
            model_name='background',
            old_name='medicine',
            new_name='Medicine',
        ),
        migrations.RenameField(
            model_name='background',
            old_name='nature',
            new_name='Nature',
        ),
        migrations.RenameField(
            model_name='background',
            old_name='perception',
            new_name='Perception',
        ),
        migrations.RenameField(
            model_name='background',
            old_name='performance',
            new_name='Performance',
        ),
        migrations.RenameField(
            model_name='background',
            old_name='persuasion',
            new_name='Persuasion',
        ),
        migrations.RenameField(
            model_name='background',
            old_name='religion',
            new_name='Religion',
        ),
        migrations.RenameField(
            model_name='background',
            old_name='sleight',
            new_name='Sleight',
        ),
        migrations.RenameField(
            model_name='background',
            old_name='stealth',
            new_name='Stealth',
        ),
        migrations.RenameField(
            model_name='background',
            old_name='survival',
            new_name='Survival',
        ),
    ]
