# Generated by Django 2.0.2 on 2018-04-07 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_auto_20180407_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='background',
            old_name='Animal_handling',
            new_name='Animal_Handling',
        ),
        migrations.RenameField(
            model_name='background',
            old_name='Sleight',
            new_name='Sleight_Of_Hand',
        ),
    ]
