# Generated by Django 2.0.2 on 2018-04-07 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_auto_20180407_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='background',
            old_name='Sleight_Of_Hand',
            new_name='Sleight_of_Hand',
        ),
    ]
