# Generated by Django 2.0.2 on 2018-04-12 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0022_auto_20180407_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spell',
            name='cleric_spell',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='druid_spell',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='sorceror_spell',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='warlock_spell',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='wizard_spell',
        ),
        migrations.AddField(
            model_name='character',
            name='account',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='spell',
            name='concentration',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='spell',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='spell',
            name='on_reaction',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='spell',
            name='save_stats',
            field=models.CharField(default=None, max_length=3),
        ),
        migrations.AddField(
            model_name='spell',
            name='spell_ac_boost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='spell',
            name='spell_class',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='game.Guild'),
        ),
        migrations.AddField(
            model_name='spell',
            name='spell_item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='game.Item'),
        ),
        migrations.AddField(
            model_name='spell',
            name='spell_length_rounds',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='spell',
            name='spell_save_dc',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='spell',
            name='spell_skill_boost_name',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='spell',
            name='spell_skill_boost_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='spell',
            name='spell_status_effect',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
