# Generated by Django 2.0.2 on 2018-04-12 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_auto_20180411_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spell',
            old_name='damage',
            new_name='damage_die',
        ),
        migrations.AddField(
            model_name='spell',
            name='damage_coefficient',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='spell',
            name='damage_constant',
            field=models.IntegerField(default=0),
        ),
    ]
