# Generated by Django 2.0.2 on 2018-04-12 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_auto_20180411_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='save_stats',
            field=models.CharField(blank=True, default=None, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='spell_class',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='game.Guild'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='spell_item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='game.Item'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='spell_skill_boost_name',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='spell_status_effect',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
