# Generated by Django 2.0.2 on 2018-04-15 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_auto_20180411_2245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spell',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='character',
            name='subguild',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='game.SubGuild'),
        ),
    ]
