# Generated by Django 2.0.2 on 2018-04-15 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0027_auto_20180415_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='subguild',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='game.SubGuild'),
        ),
    ]
