# Generated by Django 2.0.2 on 2018-04-16 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0029_auto_20180415_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='goodAlignment',
            field=models.CharField(choices=[(100, 'Good'), (50, 'Neutral'), (0, 'Evil')], default=100, max_length=20),
        ),
        migrations.AlterField(
            model_name='character',
            name='lawfulAlignment',
            field=models.CharField(choices=[(100, 'Lawful'), (50, 'Neutral'), (0, 'Chaotic')], default=100, max_length=20),
        ),
    ]
