# Generated by Django 2.0.2 on 2018-04-17 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0032_auto_20180416_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='subrace',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='game.SubRace'),
        ),
    ]
