# Generated by Django 2.0.2 on 2018-04-18 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0034_auto_20180417_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='charisma_prof',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='constitution_prof',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='dexterity_prof',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='intelligence_prof',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='strength_prof',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='wisdom_prof',
            field=models.IntegerField(default=0),
        ),
    ]
