# Generated by Django 2.0.2 on 2018-04-18 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0035_auto_20180417_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='AC',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='initiative',
            field=models.IntegerField(default=0),
        ),
    ]
