# Generated by Django 2.0.2 on 2018-04-18 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0036_auto_20180417_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='magic_dice',
            field=models.IntegerField(default=0),
        ),
    ]
