# Generated by Django 2.0.2 on 2018-04-18 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0037_guild_magic_dice'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='main_stat',
            field=models.CharField(default='DEX', max_length=3),
        ),
    ]
