# Generated by Django 2.0.2 on 2018-04-26 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0039_auto_20180425_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='cooldown',
            field=models.IntegerField(default=1),
        ),
    ]
